//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenge
    {
        public int id { get; set; }
        public int activity_id { get; set; }
        public int challenge_value { get; set; }
        public System.DateTime challenge_issued_time { get; set; }
        public System.DateTime challenge_expiration_time { get; set; }
    }
}
