//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class octopusEntities1 : DbContext
    {
        public octopusEntities1()
            : base("name=octopusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<activitytracker> activitytrackers { get; set; }
        public virtual DbSet<challenge> challenges { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<quizquestion> quizquestions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int insertQuiz(string quizname, Nullable<int> quizcount, string quizdescription, ObjectParameter identity)
        {
            var quiznameParameter = quizname != null ?
                new ObjectParameter("quizname", quizname) :
                new ObjectParameter("quizname", typeof(string));
    
            var quizcountParameter = quizcount.HasValue ?
                new ObjectParameter("quizcount", quizcount) :
                new ObjectParameter("quizcount", typeof(int));
    
            var quizdescriptionParameter = quizdescription != null ?
                new ObjectParameter("quizdescription", quizdescription) :
                new ObjectParameter("quizdescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertQuiz", quiznameParameter, quizcountParameter, quizdescriptionParameter, identity);
        }
    
        public virtual ObjectResult<selectQuizzes_Result> selectQuizzes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectQuizzes_Result>("selectQuizzes");
        }
    }
}
