//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiztaken
    {
        public int id { get; set; }
        public Nullable<int> quizid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> numberofcorrectanswers { get; set; }
        public Nullable<int> totalnumberofquestions { get; set; }
        public string failedidlist { get; set; }
    
        public virtual quiz quiz { get; set; }
    }
}
