//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus
{
    using System;
    using System.Collections.Generic;
    
    public partial class quizquestion
    {
        public int id { get; set; }
        public int quizid { get; set; }
        public string quizquestion1 { get; set; }
        public string quizanswer { get; set; }
        public string quizoptions { get; set; }
        public string quizquestiontype { get; set; }
    
        public virtual quiz quiz { get; set; }
    }
}
